/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Carga;

import java.awt.*;
import java.text.*;
import java.util.*;

/**
 *
 * @author Carolina
 */
public class frmRegistrarEnvioMuestra extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRegistrarEnvioMuestras
     */
    public frmRegistrarEnvioMuestra() {
        initComponents();
        
        txtFecha.setEnabled(false);
        txtFecha.setEditable(false);
        txtHora.setEditable(false);
        txtHora.setEnabled(false);
        //setear el campo de fecha con la del sistema
        GregorianCalendar gc=new GregorianCalendar();
        GregorianCalendar.getInstance();
        gc.setTimeZone(TimeZone.getTimeZone("GMT-3"));
        gc.get(Calendar.DAY_OF_WEEK);
        gc.get(Calendar.MONTH);
        gc.get(Calendar.YEAR);
        SimpleDateFormat formateador= new SimpleDateFormat("dd-MM-yyyy");
        txtFecha.setText(formateador.format(gc.getTime()));
        //setear el campo de hora con la del sistema
        GregorianCalendar calendario=new GregorianCalendar();
        GregorianCalendar.getInstance();
        gc.setTimeZone(TimeZone.getTimeZone("GMT-3"));
        calendario.get(Calendar.HOUR);
        calendario.get(Calendar.MINUTE);
        SimpleDateFormat formateadorHora=new SimpleDateFormat("hh:mm");
        txtHora.setText(formateadorHora.format(calendario.getTime()));
        
        //redimensionar columnas de la tabla envios
        tblEnvios.getColumnModel().getColumn(0).setPreferredWidth(30);
        tblEnvios.getColumnModel().getColumn(1).setPreferredWidth(30);
        tblEnvios.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblEnvios.getColumnModel().getColumn(3).setPreferredWidth(30);
        tblEnvios.getColumnModel().getColumn(4).setPreferredWidth(100);
        
        //redimensionar columnas de la tabla busqueda de muestras
        tblMuestra.getColumnModel().getColumn(0).setPreferredWidth(40);
        tblMuestra.getColumnModel().getColumn(1).setPreferredWidth(40);
        tblMuestra.getColumnModel().getColumn(2).setPreferredWidth(200);
        
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension tamanioPantalla = kit.getScreenSize();
        int ancho = 920;
        int alto = 635;
        this.setSize(ancho, alto);
        this.setLocation(200, 0);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMuestra = new javax.swing.JTable();
        btnAceptarMuestra = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtProductor = new javax.swing.JTextField();
        cmbEstablecimiento = new javax.swing.JComboBox();
        txtMuestra = new javax.swing.JTextField();
        cmbEspecialidad = new javax.swing.JComboBox();
        cmbLaboratorio = new javax.swing.JComboBox();
        cmbCereal = new javax.swing.JComboBox();
        calendarioEnvio = new datechooser.beans.DateChooserCombo();
        txtResponsable = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEnvios = new javax.swing.JTable();
        btnEliminarEnvio = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ckFecha = new javax.swing.JCheckBox();
        ckProductor = new javax.swing.JCheckBox();
        ckNumMuestra = new javax.swing.JCheckBox();
        ckTodos = new javax.swing.JCheckBox();
        btnBuscarMuestra = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        calendarioHMuestra = new datechooser.beans.DateChooserCombo();
        calendarioDMuestra = new datechooser.beans.DateChooserCombo();
        jPanel13 = new javax.swing.JPanel();
        cmbProductor = new javax.swing.JComboBox();
        jPanel12 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtNumMuestra = new javax.swing.JTextField();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Envio Muestra");

        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Fecha");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(10, 11, 70, 20);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Hora");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(180, 10, 50, 20);
        jPanel3.add(txtFecha);
        txtFecha.setBounds(50, 10, 70, 20);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Usuario");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(770, 10, 70, 15);

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UsuarioLogueado.png"))); // NOI18N
        jPanel3.add(jLabel48);
        jLabel48.setBounds(820, 0, 32, 32);
        jPanel3.add(txtHora);
        txtHora.setBounds(210, 10, 70, 20);

        tblMuestra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Nº Muestra", "Productor"
            }
        ));
        jScrollPane1.setViewportView(tblMuestra);

        btnAceptarMuestra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar.png"))); // NOI18N

        jPanel1.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Productor");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 10, 90, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Establecimiento");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(320, 10, 130, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Laboratorio");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(350, 40, 90, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Especialidad");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 40, 110, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Nº Muestra");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(670, 10, 100, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Fecha Envío");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 70, 100, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Cereal");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(690, 40, 70, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Responsable");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(340, 70, 120, 20);
        jPanel1.add(txtProductor);
        txtProductor.setBounds(90, 10, 200, 20);

        jPanel1.add(cmbEstablecimiento);
        cmbEstablecimiento.setBounds(420, 10, 210, 20);
        jPanel1.add(txtMuestra);
        txtMuestra.setBounds(740, 10, 100, 20);

        jPanel1.add(cmbEspecialidad);
        cmbEspecialidad.setBounds(90, 40, 200, 20);

        jPanel1.add(cmbLaboratorio);
        cmbLaboratorio.setBounds(420, 40, 210, 20);

        jPanel1.add(cmbCereal);
        cmbCereal.setBounds(740, 40, 100, 20);
        jPanel1.add(calendarioEnvio);
        calendarioEnvio.setBounds(90, 70, 90, 20);
        jPanel1.add(txtResponsable);
        txtResponsable.setBounds(420, 70, 170, 20);

        tblEnvios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha Envío", "Nº Muestra", "Productor", "Cereal", "Laboratorio"
            }
        ));
        jScrollPane2.setViewportView(tblEnvios);

        btnEliminarEnvio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");

        btnNuevo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icononuevo.PNG"))); // NOI18N
        btnNuevo.setText("Nuevo");

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        btnAgregar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Agregar.png"))); // NOI18N
        btnAgregar.setText("Agregar");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Muestras por", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel2.setLayout(null);

        ckFecha.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ckFecha.setText("Fecha");
        jPanel2.add(ckFecha);
        ckFecha.setBounds(80, 20, 80, 23);

        ckProductor.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ckProductor.setText("Productor");
        jPanel2.add(ckProductor);
        ckProductor.setBounds(290, 20, 110, 23);

        ckNumMuestra.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ckNumMuestra.setText("Nº Muestra");
        jPanel2.add(ckNumMuestra);
        ckNumMuestra.setBounds(510, 20, 100, 23);

        ckTodos.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ckTodos.setText("Todos");
        jPanel2.add(ckTodos);
        ckTodos.setBounds(720, 20, 80, 23);

        btnBuscarMuestra.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnBuscarMuestra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        btnBuscarMuestra.setText("Buscar");
        jPanel2.add(btnBuscarMuestra);
        btnBuscarMuestra.setBounds(380, 130, 104, 30);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel10.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Desde");
        jPanel10.add(jLabel12);
        jLabel12.setBounds(40, 20, 60, 20);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Hasta");
        jPanel10.add(jLabel15);
        jLabel15.setBounds(40, 50, 60, 20);
        jPanel10.add(calendarioHMuestra);
        calendarioHMuestra.setBounds(80, 50, 90, 20);
        jPanel10.add(calendarioDMuestra);
        calendarioDMuestra.setBounds(80, 20, 90, 20);

        jPanel2.add(jPanel10);
        jPanel10.setBounds(40, 40, 230, 90);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel13.setLayout(null);

        jPanel13.add(cmbProductor);
        cmbProductor.setBounds(40, 40, 200, 20);

        jPanel2.add(jPanel13);
        jPanel13.setBounds(300, 40, 280, 90);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nº Muestra", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel12.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Nº");
        jPanel12.add(jLabel16);
        jLabel16.setBounds(30, 40, 50, 20);
        jPanel12.add(txtNumMuestra);
        txtNumMuestra.setBounds(50, 40, 120, 20);

        jPanel2.add(jPanel12);
        jPanel12.setBounds(610, 40, 220, 90);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAceptarMuestra)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNuevo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addGap(312, 312, 312))))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEliminarEnvio))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 877, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(381, 381, 381)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnAceptarMuestra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnEliminarEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptarMuestra;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscarMuestra;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminarEnvio;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private datechooser.beans.DateChooserCombo calendarioDMuestra;
    private datechooser.beans.DateChooserCombo calendarioEnvio;
    private datechooser.beans.DateChooserCombo calendarioHMuestra;
    private javax.swing.JCheckBox ckFecha;
    private javax.swing.JCheckBox ckNumMuestra;
    private javax.swing.JCheckBox ckProductor;
    private javax.swing.JCheckBox ckTodos;
    private javax.swing.JComboBox cmbCereal;
    private javax.swing.JComboBox cmbEspecialidad;
    private javax.swing.JComboBox cmbEstablecimiento;
    private javax.swing.JComboBox cmbLaboratorio;
    private javax.swing.JComboBox cmbProductor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEnvios;
    private javax.swing.JTable tblMuestra;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtMuestra;
    private javax.swing.JTextField txtNumMuestra;
    private javax.swing.JTextField txtProductor;
    private javax.swing.JTextField txtResponsable;
    // End of variables declaration//GEN-END:variables
}
