/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas_Carga;

import java.awt.*;
import java.text.*;
import java.util.*;


/**
 *
 * @author Carolina
 */
public class frmRegistrarResultadosLab extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmRegistrarResultadosLab
     */
    public frmRegistrarResultadosLab() {
        initComponents();
        
        txtHora.setEditable(false);
        txtHora.setEnabled(false);
        txtHora.setEnabled(false);
        txtHora.setEditable(false);
        txtFecha.setEditable(false);
        txtFecha.setEnabled(false);
        txtFecha.setEditable(false);
        txtFecha.setEnabled(false);
        //setear el campo de fecha con la del sistema
        GregorianCalendar gc=new GregorianCalendar();
        GregorianCalendar.getInstance();
        gc.setTimeZone(TimeZone.getTimeZone("GMT-3"));
        gc.get(Calendar.DAY_OF_WEEK);
        gc.get(Calendar.MONTH);
        gc.get(Calendar.YEAR);
        SimpleDateFormat formateador= new SimpleDateFormat("dd-MM-yyyy");
        txtFecha.setText(formateador.format(gc.getTime()));
        txtFecha.setText(formateador.format(gc.getTime()));
        //setear el campo de hora con la del sistema
        GregorianCalendar calendario=new GregorianCalendar();
        GregorianCalendar.getInstance();
        gc.setTimeZone(TimeZone.getTimeZone("GMT-3"));
        calendario.get(Calendar.HOUR);
        calendario.get(Calendar.MINUTE);
        SimpleDateFormat formateadorHora=new SimpleDateFormat("hh:mm");
        txtHora.setText(formateadorHora.format(calendario.getTime()));
        txtHora.setText(formateadorHora.format(calendario.getTime()));
        
        
        //Las siguientes lineas son para dar a la pantalla el tamaño requerido y luego centrarla en la pantalla.
        Toolkit kit = Toolkit.getDefaultToolkit();
        Dimension tamanioPantalla = kit.getScreenSize();
        int ancho = 1150;
        int alto = 630;
        int posX = (int) ((tamanioPantalla.width - ancho) / 2);
//        int posY = (int) ((tamanioPantalla.height - alto) / 2);
        this.setSize(ancho, alto);
        this.setLocation(posX, 0);
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btnAceptarViaje = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ckFecha = new javax.swing.JCheckBox();
        ckNumViaje = new javax.swing.JCheckBox();
        ckProductor = new javax.swing.JCheckBox();
        ckTransportista = new javax.swing.JCheckBox();
        ckEstablecimiento = new javax.swing.JCheckBox();
        ckTodos = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        cmbEstablecimiento = new javax.swing.JComboBox();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        calendarioHViaje = new datechooser.beans.DateChooserCombo();
        calendarioDViaje = new datechooser.beans.DateChooserCombo();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtNumViaje = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        cmbProductor = new javax.swing.JComboBox();
        jPanel14 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox();
        btnBuscarViaje = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtViaje = new javax.swing.JTextField();
        txtFechaViaje = new javax.swing.JTextField();
        txtProductor = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        txtEstablecimiento = new javax.swing.JTextField();
        txtHas = new javax.swing.JTextField();
        txNumLote = new javax.swing.JTextField();
        txtTransportista = new javax.swing.JTextField();
        txtVehiculo = new javax.swing.JTextField();
        txtNumMuestra = new javax.swing.JTextField();
        txtTempCosecha = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtCereal = new javax.swing.JTextField();
        txtToneladas = new javax.swing.JTextField();
        txtImpurezas = new javax.swing.JTextField();
        txtPesoHect = new javax.swing.JTextField();
        txtDominio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtHumedad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViaje = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        cmbLaboratorio = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtDomicilioLab = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtLocalidadLab = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtTelefonoLab = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtProvinciaLab = new javax.swing.JTextField();
        cmbEspecialidad = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        calendarioRecep = new datechooser.beans.DateChooserCombo();
        calendarioEnvio = new datechooser.beans.DateChooserCombo();
        jLabel32 = new javax.swing.JLabel();
        txtMuestraLab = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        botonMaiz = new javax.swing.JRadioButton();
        botonSoja = new javax.swing.JRadioButton();
        botonTrigo = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtDurezaObtenida = new javax.swing.JTextField();
        txtDurezaNormal = new javax.swing.JTextField();
        txtProtNormal = new javax.swing.JTextField();
        txtGlutenNormal = new javax.swing.JTextField();
        txtAlmidonNormal = new javax.swing.JTextField();
        txtProtObtenidas = new javax.swing.JTextField();
        txtGlutenObtenido = new javax.swing.JTextField();
        txtColorNormal = new javax.swing.JTextField();
        txtAlmidonObtenido = new javax.swing.JTextField();
        txtColorObtenido = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Resultados Analisis");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Fecha");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Hora");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Usuario");

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/UsuarioLogueado.png"))); // NOI18N

        btnAceptarViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Aceptar.png"))); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar Viajes Finalizados por", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel5.setLayout(null);

        ckFecha.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ckFecha.setText("Fecha");
        jPanel5.add(ckFecha);
        ckFecha.setBounds(60, 20, 60, 23);

        ckNumViaje.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ckNumViaje.setText("Numero Viaje");
        jPanel5.add(ckNumViaje);
        ckNumViaje.setBounds(180, 20, 110, 23);

        ckProductor.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ckProductor.setText("Productor");
        jPanel5.add(ckProductor);
        ckProductor.setBounds(330, 20, 90, 23);

        ckTransportista.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ckTransportista.setText("Transportista");
        jPanel5.add(ckTransportista);
        ckTransportista.setBounds(460, 20, 120, 23);

        ckEstablecimiento.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ckEstablecimiento.setText("Establecimiento");
        jPanel5.add(ckEstablecimiento);
        ckEstablecimiento.setBounds(600, 20, 120, 23);

        ckTodos.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        ckTodos.setText("Todos");
        jPanel5.add(ckTodos);
        ckTodos.setBounds(740, 20, 81, 23);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Establecimiento", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel9.setLayout(null);

        jPanel9.add(cmbEstablecimiento);
        cmbEstablecimiento.setBounds(20, 40, 200, 20);

        jPanel5.add(jPanel9);
        jPanel9.setBounds(570, 50, 240, 90);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel10.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setText("Desde");
        jPanel10.add(jLabel7);
        jLabel7.setBounds(10, 20, 60, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setText("Hasta");
        jPanel10.add(jLabel10);
        jLabel10.setBounds(10, 50, 60, 20);
        jPanel10.add(calendarioHViaje);
        calendarioHViaje.setBounds(50, 50, 90, 20);
        jPanel10.add(calendarioDViaje);
        calendarioDViaje.setBounds(50, 20, 90, 20);

        jPanel5.add(jPanel10);
        jPanel10.setBounds(10, 50, 160, 90);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nº Viaje", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel12.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setText("Nº");
        jPanel12.add(jLabel11);
        jLabel11.setBounds(20, 40, 50, 20);
        jPanel12.add(txtNumViaje);
        txtNumViaje.setBounds(40, 40, 100, 20);

        jPanel5.add(jPanel12);
        jPanel12.setBounds(170, 50, 160, 90);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel13.setLayout(null);

        jPanel13.add(cmbProductor);
        cmbProductor.setBounds(20, 40, 200, 20);

        jPanel5.add(jPanel13);
        jPanel13.setBounds(330, 50, 240, 90);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transportista", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jPanel14.setLayout(null);

        jPanel14.add(jComboBox3);
        jComboBox3.setBounds(20, 40, 200, 20);

        jPanel5.add(jPanel14);
        jPanel14.setBounds(810, 50, 240, 90);

        btnBuscarViaje.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnBuscarViaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/lupa.png"))); // NOI18N
        btnBuscarViaje.setText("Buscar");
        jPanel5.add(btnBuscarViaje);
        btnBuscarViaje.setBounds(500, 150, 100, 30);

        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setText("Establecimiento");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(20, 40, 120, 20);

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setText("Productor");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(360, 10, 90, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setText("Domicilio");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(640, 10, 90, 20);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText("Vehiculo");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(370, 70, 80, 20);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText("Muestra Nº");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(40, 100, 100, 20);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setText("Fecha");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(170, 10, 60, 20);

        jLabel21.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel21.setText("Temporada Cosecha");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(290, 100, 150, 20);

        jLabel20.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel20.setText("Toneladas");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(660, 100, 90, 20);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setText("Lote Nº");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(370, 40, 80, 20);

        jLabel23.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel23.setText("Peso Hectolítrico");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(10, 130, 130, 20);

        jLabel22.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel22.setText("Impurezas");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(660, 130, 80, 20);

        jLabel35.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel35.setText("% Humedad");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(340, 130, 100, 20);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setText("Nº Viaje");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 10, 70, 20);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setText("Hectáreas");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(550, 40, 100, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Transportista");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(30, 70, 110, 20);
        jPanel4.add(txtViaje);
        txtViaje.setBounds(60, 10, 80, 20);
        jPanel4.add(txtFechaViaje);
        txtFechaViaje.setBounds(210, 10, 90, 20);
        jPanel4.add(txtProductor);
        txtProductor.setBounds(420, 10, 180, 20);
        jPanel4.add(txtDomicilio);
        txtDomicilio.setBounds(700, 10, 220, 20);
        jPanel4.add(txtEstablecimiento);
        txtEstablecimiento.setBounds(110, 40, 200, 20);
        jPanel4.add(txtHas);
        txtHas.setBounds(610, 40, 90, 20);
        jPanel4.add(txNumLote);
        txNumLote.setBounds(420, 40, 90, 20);
        jPanel4.add(txtTransportista);
        txtTransportista.setBounds(110, 70, 200, 20);
        jPanel4.add(txtVehiculo);
        txtVehiculo.setBounds(420, 70, 200, 20);
        jPanel4.add(txtNumMuestra);
        txtNumMuestra.setBounds(110, 100, 90, 20);
        jPanel4.add(txtTempCosecha);
        txtTempCosecha.setBounds(420, 100, 90, 20);

        jLabel42.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel42.setText("Cereal");
        jPanel4.add(jLabel42);
        jLabel42.setBounds(750, 40, 80, 20);
        jPanel4.add(txtCereal);
        txtCereal.setBounds(790, 40, 100, 20);
        jPanel4.add(txtToneladas);
        txtToneladas.setBounds(720, 100, 90, 20);
        jPanel4.add(txtImpurezas);
        txtImpurezas.setBounds(720, 130, 90, 20);
        jPanel4.add(txtPesoHect);
        txtPesoHect.setBounds(110, 130, 90, 20);
        jPanel4.add(txtDominio);
        txtDominio.setBounds(720, 70, 90, 20);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setText("Dominio");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(670, 70, 70, 20);
        jPanel4.add(txtHumedad);
        txtHumedad.setBounds(420, 130, 90, 20);

        tblViaje.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Nº Viaje", "Productor", "Establecimiento", "Transportista"
            }
        ));
        jScrollPane1.setViewportView(tblViaje);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 57, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 945, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btnAceptarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btnAceptarViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jTabbedPane1.addTab("Datos Muestra", jPanel2);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Laboratorio", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel7.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel26.setText("Especialidad");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(30, 30, 110, 20);

        jPanel7.add(cmbLaboratorio);
        cmbLaboratorio.setBounds(470, 30, 247, 20);

        jLabel27.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel27.setText("Laboratorio");
        jPanel7.add(jLabel27);
        jLabel27.setBounds(400, 30, 110, 20);

        jLabel28.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel28.setText("Domicilio");
        jPanel7.add(jLabel28);
        jLabel28.setBounds(50, 60, 70, 20);
        jPanel7.add(txtDomicilioLab);
        txtDomicilioLab.setBounds(110, 60, 250, 20);

        jLabel29.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel29.setText("Localidad");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(410, 60, 80, 20);
        jPanel7.add(txtLocalidadLab);
        txtLocalidadLab.setBounds(470, 60, 250, 20);

        jLabel30.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel30.setText("Provincia");
        jPanel7.add(jLabel30);
        jLabel30.setBounds(50, 90, 60, 20);
        jPanel7.add(txtTelefonoLab);
        txtTelefonoLab.setBounds(470, 90, 250, 20);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel31.setText("Telefono");
        jPanel7.add(jLabel31);
        jLabel31.setBounds(410, 90, 80, 20);
        jPanel7.add(txtProvinciaLab);
        txtProvinciaLab.setBounds(110, 90, 250, 20);

        jPanel7.add(cmbEspecialidad);
        cmbEspecialidad.setBounds(110, 30, 247, 20);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados Analisis", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel6.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel24.setText("Fecha Envio");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(330, 30, 100, 20);

        jLabel25.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel25.setText("Fecha Recepción");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(580, 30, 120, 20);
        jPanel6.add(calendarioRecep);
        calendarioRecep.setBounds(680, 30, 110, 20);
        jPanel6.add(calendarioEnvio);
        calendarioEnvio.setBounds(400, 30, 110, 20);

        jLabel32.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel32.setText("Muestra Nº");
        jPanel6.add(jLabel32);
        jLabel32.setBounds(60, 30, 100, 20);
        jPanel6.add(txtMuestraLab);
        txtMuestraLab.setBounds(130, 30, 100, 20);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cereal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N
        jPanel11.setLayout(null);

        botonMaiz.setText("Maiz");
        jPanel11.add(botonMaiz);
        botonMaiz.setBounds(40, 20, 50, 23);

        botonSoja.setText("Soja");
        jPanel11.add(botonSoja);
        botonSoja.setBounds(190, 20, 50, 23);

        botonTrigo.setText("Trigo");
        jPanel11.add(botonTrigo);
        botonTrigo.setBounds(330, 20, 60, 23);

        jPanel6.add(jPanel11);
        jPanel11.setBounds(240, 70, 440, 50);
        jPanel6.add(jSeparator1);
        jSeparator1.setBounds(30, 60, 850, 10);

        jLabel33.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel33.setText("Dureza");
        jPanel6.add(jLabel33);
        jLabel33.setBounds(140, 160, 120, 20);

        jLabel34.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel34.setText("Nivel de Proteínas");
        jPanel6.add(jLabel34);
        jLabel34.setBounds(140, 190, 130, 20);

        jLabel36.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel36.setText("Nivel de Gluten");
        jPanel6.add(jLabel36);
        jLabel36.setBounds(140, 220, 140, 20);

        jLabel37.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel37.setText("Color");
        jPanel6.add(jLabel37);
        jLabel37.setBounds(140, 250, 110, 20);

        jLabel38.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel38.setText("Almidon");
        jPanel6.add(jLabel38);
        jLabel38.setBounds(140, 280, 100, 20);

        jLabel39.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel39.setText("Valores Obtenidos");
        jPanel6.add(jLabel39);
        jLabel39.setBounds(520, 130, 110, 15);

        jLabel40.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel40.setText("Valores Normales");
        jPanel6.add(jLabel40);
        jLabel40.setBounds(330, 130, 110, 15);
        jPanel6.add(txtDurezaObtenida);
        txtDurezaObtenida.setBounds(520, 160, 100, 20);

        txtDurezaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurezaNormalActionPerformed(evt);
            }
        });
        jPanel6.add(txtDurezaNormal);
        txtDurezaNormal.setBounds(330, 160, 100, 20);

        txtProtNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProtNormalActionPerformed(evt);
            }
        });
        jPanel6.add(txtProtNormal);
        txtProtNormal.setBounds(330, 190, 100, 20);

        txtGlutenNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGlutenNormalActionPerformed(evt);
            }
        });
        jPanel6.add(txtGlutenNormal);
        txtGlutenNormal.setBounds(330, 220, 100, 20);

        txtAlmidonNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlmidonNormalActionPerformed(evt);
            }
        });
        jPanel6.add(txtAlmidonNormal);
        txtAlmidonNormal.setBounds(330, 280, 100, 20);

        txtProtObtenidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProtObtenidasActionPerformed(evt);
            }
        });
        jPanel6.add(txtProtObtenidas);
        txtProtObtenidas.setBounds(520, 190, 100, 20);

        txtGlutenObtenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGlutenObtenidoActionPerformed(evt);
            }
        });
        jPanel6.add(txtGlutenObtenido);
        txtGlutenObtenido.setBounds(520, 220, 100, 20);

        txtColorNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorNormalActionPerformed(evt);
            }
        });
        jPanel6.add(txtColorNormal);
        txtColorNormal.setBounds(330, 250, 100, 20);

        txtAlmidonObtenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlmidonObtenidoActionPerformed(evt);
            }
        });
        jPanel6.add(txtAlmidonObtenido);
        txtAlmidonObtenido.setBounds(520, 280, 100, 20);

        txtColorObtenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorObtenidoActionPerformed(evt);
            }
        });
        jPanel6.add(txtColorObtenido);
        txtColorObtenido.setBounds(520, 250, 100, 20);
        jPanel6.add(jSeparator2);
        jSeparator2.setBounds(30, 150, 850, 10);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos Analisis", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(jLabel48))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnNuevo.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icononuevo.PNG"))); // NOI18N
        btnNuevo.setText("Nuevo");

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");

        btnGuardar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(434, 434, 434)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDurezaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurezaNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurezaNormalActionPerformed

    private void txtProtNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProtNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProtNormalActionPerformed

    private void txtGlutenNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGlutenNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGlutenNormalActionPerformed

    private void txtAlmidonNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlmidonNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlmidonNormalActionPerformed

    private void txtProtObtenidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProtObtenidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProtObtenidasActionPerformed

    private void txtGlutenObtenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGlutenObtenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGlutenObtenidoActionPerformed

    private void txtColorNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorNormalActionPerformed

    private void txtAlmidonObtenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlmidonObtenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlmidonObtenidoActionPerformed

    private void txtColorObtenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorObtenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorObtenidoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton botonMaiz;
    private javax.swing.JRadioButton botonSoja;
    private javax.swing.JRadioButton botonTrigo;
    private javax.swing.JButton btnAceptarViaje;
    private javax.swing.JButton btnBuscarViaje;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private datechooser.beans.DateChooserCombo calendarioDViaje;
    private datechooser.beans.DateChooserCombo calendarioEnvio;
    private datechooser.beans.DateChooserCombo calendarioHViaje;
    private datechooser.beans.DateChooserCombo calendarioRecep;
    private javax.swing.JCheckBox ckEstablecimiento;
    private javax.swing.JCheckBox ckFecha;
    private javax.swing.JCheckBox ckNumViaje;
    private javax.swing.JCheckBox ckProductor;
    private javax.swing.JCheckBox ckTodos;
    private javax.swing.JCheckBox ckTransportista;
    private javax.swing.JComboBox cmbEspecialidad;
    private javax.swing.JComboBox cmbEstablecimiento;
    private javax.swing.JComboBox cmbLaboratorio;
    private javax.swing.JComboBox cmbProductor;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblViaje;
    private javax.swing.JTextField txNumLote;
    private javax.swing.JTextField txtAlmidonNormal;
    private javax.swing.JTextField txtAlmidonObtenido;
    private javax.swing.JTextField txtCereal;
    private javax.swing.JTextField txtColorNormal;
    private javax.swing.JTextField txtColorObtenido;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtDomicilioLab;
    private javax.swing.JTextField txtDominio;
    private javax.swing.JTextField txtDurezaNormal;
    private javax.swing.JTextField txtDurezaObtenida;
    private javax.swing.JTextField txtEstablecimiento;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtFechaViaje;
    private javax.swing.JTextField txtGlutenNormal;
    private javax.swing.JTextField txtGlutenObtenido;
    private javax.swing.JTextField txtHas;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtHumedad;
    private javax.swing.JTextField txtImpurezas;
    private javax.swing.JTextField txtLocalidadLab;
    private javax.swing.JTextField txtMuestraLab;
    private javax.swing.JTextField txtNumMuestra;
    private javax.swing.JTextField txtNumViaje;
    private javax.swing.JTextField txtPesoHect;
    private javax.swing.JTextField txtProductor;
    private javax.swing.JTextField txtProtNormal;
    private javax.swing.JTextField txtProtObtenidas;
    private javax.swing.JTextField txtProvinciaLab;
    private javax.swing.JTextField txtTelefonoLab;
    private javax.swing.JTextField txtTempCosecha;
    private javax.swing.JTextField txtToneladas;
    private javax.swing.JTextField txtTransportista;
    private javax.swing.JTextField txtVehiculo;
    private javax.swing.JTextField txtViaje;
    // End of variables declaration//GEN-END:variables
}
